from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4


def create_report(
    username,
    career,
    difficulty,
    score,
    max_score,
    percentage
):

    filename = f"{username}_Interview_Report.pdf"

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    story = []

    # ==================================================
    # TITLE
    # ==================================================

    story.append(
        Paragraph(
            "🎤 <b>InterviewAce</b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "AI Interview Preparation Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 20))

    # ==================================================
    # CANDIDATE INFORMATION
    # ==================================================

    story.append(
        Paragraph(
            "<b>Candidate Information</b>",
            styles["Heading2"]
        )
    )

    candidate_data = [
        ["Candidate", username],
        ["Career", career],
        ["Difficulty", difficulty],
        ["Score", f"{score}/{max_score}"],
        ["Percentage", f"{percentage:.1f}%"]
    ]

    table = Table(
        candidate_data,
        colWidths=[150, 300]
    )

    table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("PADDING", (0, 0), (-1, -1), 8)
        ])
    )

    story.append(table)

    story.append(Spacer(1, 25))

    # ==================================================
    # PERFORMANCE
    # ==================================================

    story.append(
        Paragraph(
            "<b>Performance Analysis</b>",
            styles["Heading2"]
        )
    )

    if percentage >= 80:

        result = "Excellent - Interview Ready"

        recommendation = (
            "Excellent performance! Continue practicing "
            "advanced questions and real-world examples."
        )

    elif percentage >= 60:

        result = "Good - Keep Practicing"

        recommendation = (
            "Good performance. Review the concepts you "
            "missed and practice more technical examples."
        )

    else:

        result = "Needs More Practice"

        recommendation = (
            "Focus on the basic concepts and practice "
            "answering interview questions regularly."
        )

    story.append(
        Paragraph(
            f"<b>Performance:</b> {result}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Recommendation:</b> {recommendation}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 25))

    # ==================================================
    # SUMMARY
    # ==================================================

    story.append(
        Paragraph(
            "<b>Interview Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"You completed an InterviewAce mock interview "
            f"for the <b>{career}</b> career path at "
            f"<b>{difficulty}</b> difficulty.",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"Your final score was "
            f"<b>{score}/{max_score}</b>, "
            f"which represents <b>{percentage:.1f}%</b>.",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 25))

    # ==================================================
    # FOOTER
    # ==================================================

    story.append(
        Paragraph(
            "<i>Generated by InterviewAce</i>",
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename